export interface City {
  id: string
  name: string
  /** Short airport-style code, used where space is tight (tiles, map). */
  code: string
  timeZone: string
  lat: number
  lon: number
}

export const cities: City[] = [
  {
    id: 'honolulu',
    name: 'Honolulu',
    code: 'HNL',
    timeZone: 'Pacific/Honolulu',
    lat: 21.31,
    lon: -157.86,
  },
  {
    id: 'anchorage',
    name: 'Anchorage',
    code: 'ANC',
    timeZone: 'America/Anchorage',
    lat: 61.22,
    lon: -149.9,
  },
  {
    id: 'los-angeles',
    name: 'Los Angeles',
    code: 'LAX',
    timeZone: 'America/Los_Angeles',
    lat: 34.05,
    lon: -118.24,
  },
  {
    id: 'san-francisco',
    name: 'San Francisco',
    code: 'SFO',
    timeZone: 'America/Los_Angeles',
    lat: 37.77,
    lon: -122.42,
  },
  {
    id: 'vancouver',
    name: 'Vancouver',
    code: 'YVR',
    timeZone: 'America/Vancouver',
    lat: 49.28,
    lon: -123.12,
  },
  {
    id: 'denver',
    name: 'Denver',
    code: 'DEN',
    timeZone: 'America/Denver',
    lat: 39.74,
    lon: -104.99,
  },
  {
    id: 'mexico-city',
    name: 'Mexico City',
    code: 'MEX',
    timeZone: 'America/Mexico_City',
    lat: 19.43,
    lon: -99.13,
  },
  {
    id: 'chicago',
    name: 'Chicago',
    code: 'CHI',
    timeZone: 'America/Chicago',
    lat: 41.88,
    lon: -87.63,
  },
  {
    id: 'toronto',
    name: 'Toronto',
    code: 'YYZ',
    timeZone: 'America/Toronto',
    lat: 43.65,
    lon: -79.38,
  },
  {
    id: 'new-york',
    name: 'New York',
    code: 'NYC',
    timeZone: 'America/New_York',
    lat: 40.71,
    lon: -74.01,
  },
  {
    id: 'bogota',
    name: 'Bogotá',
    code: 'BOG',
    timeZone: 'America/Bogota',
    lat: 4.71,
    lon: -74.07,
  },
  {
    id: 'sao-paulo',
    name: 'São Paulo',
    code: 'SAO',
    timeZone: 'America/Sao_Paulo',
    lat: -23.55,
    lon: -46.63,
  },
  {
    id: 'buenos-aires',
    name: 'Buenos Aires',
    code: 'BUE',
    timeZone: 'America/Argentina/Buenos_Aires',
    lat: -34.6,
    lon: -58.38,
  },
  {
    id: 'reykjavik',
    name: 'Reykjavík',
    code: 'REK',
    timeZone: 'Atlantic/Reykjavik',
    lat: 64.15,
    lon: -21.94,
  },
  {
    id: 'lisbon',
    name: 'Lisbon',
    code: 'LIS',
    timeZone: 'Europe/Lisbon',
    lat: 38.72,
    lon: -9.14,
  },
  {
    id: 'london',
    name: 'London',
    code: 'LON',
    timeZone: 'Europe/London',
    lat: 51.51,
    lon: -0.13,
  },
  {
    id: 'paris',
    name: 'Paris',
    code: 'PAR',
    timeZone: 'Europe/Paris',
    lat: 48.86,
    lon: 2.35,
  },
  {
    id: 'madrid',
    name: 'Madrid',
    code: 'MAD',
    timeZone: 'Europe/Madrid',
    lat: 40.42,
    lon: -3.7,
  },
  {
    id: 'berlin',
    name: 'Berlin',
    code: 'BER',
    timeZone: 'Europe/Berlin',
    lat: 52.52,
    lon: 13.4,
  },
  {
    id: 'rome',
    name: 'Rome',
    code: 'ROM',
    timeZone: 'Europe/Rome',
    lat: 41.9,
    lon: 12.5,
  },
  {
    id: 'milan',
    name: 'Milan',
    code: 'MIL',
    timeZone: 'Europe/Rome',
    lat: 45.46,
    lon: 9.19,
  },
  {
    id: 'stockholm',
    name: 'Stockholm',
    code: 'STO',
    timeZone: 'Europe/Stockholm',
    lat: 59.33,
    lon: 18.07,
  },
  {
    id: 'athens',
    name: 'Athens',
    code: 'ATH',
    timeZone: 'Europe/Athens',
    lat: 37.98,
    lon: 23.73,
  },
  {
    id: 'cairo',
    name: 'Cairo',
    code: 'CAI',
    timeZone: 'Africa/Cairo',
    lat: 30.04,
    lon: 31.24,
  },
  {
    id: 'lagos',
    name: 'Lagos',
    code: 'LOS',
    timeZone: 'Africa/Lagos',
    lat: 6.52,
    lon: 3.38,
  },
  {
    id: 'johannesburg',
    name: 'Johannesburg',
    code: 'JNB',
    timeZone: 'Africa/Johannesburg',
    lat: -26.2,
    lon: 28.05,
  },
  {
    id: 'nairobi',
    name: 'Nairobi',
    code: 'NBO',
    timeZone: 'Africa/Nairobi',
    lat: -1.29,
    lon: 36.82,
  },
  {
    id: 'istanbul',
    name: 'Istanbul',
    code: 'IST',
    timeZone: 'Europe/Istanbul',
    lat: 41.01,
    lon: 28.98,
  },
  {
    id: 'moscow',
    name: 'Moscow',
    code: 'MOW',
    timeZone: 'Europe/Moscow',
    lat: 55.76,
    lon: 37.62,
  },
  {
    id: 'dubai',
    name: 'Dubai',
    code: 'DXB',
    timeZone: 'Asia/Dubai',
    lat: 25.2,
    lon: 55.27,
  },
  {
    id: 'mumbai',
    name: 'Mumbai',
    code: 'BOM',
    timeZone: 'Asia/Kolkata',
    lat: 19.08,
    lon: 72.88,
  },
  {
    id: 'kathmandu',
    name: 'Kathmandu',
    code: 'KTM',
    timeZone: 'Asia/Kathmandu',
    lat: 27.72,
    lon: 85.32,
  },
  {
    id: 'bangkok',
    name: 'Bangkok',
    code: 'BKK',
    timeZone: 'Asia/Bangkok',
    lat: 13.76,
    lon: 100.5,
  },
  {
    id: 'singapore',
    name: 'Singapore',
    code: 'SIN',
    timeZone: 'Asia/Singapore',
    lat: 1.35,
    lon: 103.82,
  },
  {
    id: 'hong-kong',
    name: 'Hong Kong',
    code: 'HKG',
    timeZone: 'Asia/Hong_Kong',
    lat: 22.32,
    lon: 114.17,
  },
  {
    id: 'beijing',
    name: 'Beijing',
    code: 'PEK',
    timeZone: 'Asia/Shanghai',
    lat: 39.9,
    lon: 116.41,
  },
  {
    id: 'seoul',
    name: 'Seoul',
    code: 'SEL',
    timeZone: 'Asia/Seoul',
    lat: 37.57,
    lon: 126.98,
  },
  {
    id: 'tokyo',
    name: 'Tokyo',
    code: 'TYO',
    timeZone: 'Asia/Tokyo',
    lat: 35.68,
    lon: 139.69,
  },
  {
    id: 'sydney',
    name: 'Sydney',
    code: 'SYD',
    timeZone: 'Australia/Sydney',
    lat: -33.87,
    lon: 151.21,
  },
  {
    id: 'auckland',
    name: 'Auckland',
    code: 'AKL',
    timeZone: 'Pacific/Auckland',
    lat: -36.85,
    lon: 174.76,
  },
]

const byId = new Map(cities.map((city) => [city.id, city]))

export function getCity(id: string): City | undefined {
  return byId.get(id)
}

/** Resolves a list of ids, silently dropping unknown ones. */
export function resolveCities(ids: readonly string[]): City[] {
  return ids.map((id) => byId.get(id)).filter((city) => city !== undefined)
}
